package com.industries118.game;

import android.os.Bundle;
import com.badlogic.gdx.backends.android.AndroidApplication;
import com.badlogic.gdx.backends.android.AndroidApplicationConfiguration;

public class AndroidLauncher extends AndroidApplication
{
	AndroidActionResolver ar;
	/*	Create an AndroidActionResolver to pass to the LibGdx GameEntry class,
		since LibGdx core can't access android functions, AndroidActionResolver implements
		ActionResolver, (A class created and recognised in LibGdx core) so that the core can
		recognise it as an ActionResolver and use all the methods contained, which are overridden
		in the AndroidActionResolver class, enabling access to android Objects such as Toasts,
		Notifications, and Contexts
	*/

	//Called when launcher starts
	@Override
	protected void onCreate (Bundle savedInstanceState)
	{
		super.onCreate(savedInstanceState); //AutoGenerated
		ar = new AndroidActionResolver(getApplicationContext()); //Initialise AAR
		AndroidApplicationConfiguration config = new AndroidApplicationConfiguration();	//AutoGenerated
		initialize(new GameEntry(ar), config);	//Start running the GameEntry class, which extends LibGdx Game
	}
}
